server:
  port: 9000
  tomcat:
    min-spare-threads: 3
    max-threads: 500
    max-connections: 1000

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_service?useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=GMT
    sql-script-encoding: utf-8
    username: root
    password: 12345678
    initialSize: 3
    minIdle: 3
    maxActive: 100
    maxWait: 10000 # 获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁
    timeBetweenEvictionRunsMillis: 120000 # 有两个含义：1) Destroy线程会检测连接的间隔时间，如果连接空闲时间大于等于minEvictableIdleTimeMillis则关闭物理连接。2) testWhileIdle的判断依据，详细看testWhileIdle属性的说明
    minEvictableIdleTimeMillis: 300000 # 一个连接在池中最小生存的时间，单位是毫秒
    validationQuery: SELECT 'x' # 用来检测连接是否有效的sql，要求是一个查询语句，常用select 'x'。如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会起作用
    validationQueryTimeout: 1 # 单位：秒，检测连接是否有效的超时时间。底层调用jdbc Statement对象的void setQueryTimeout(int seconds)方法
    testWhileIdle: true # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
    testOnBorrow: false # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    testOnReturn: false # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    poolPreparedStatements: false # 是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭
    maxPoolPreparedStatementPerConnectionSize: 20  # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
    removeAbandoned: true
    removeAbandonedTimeoutMillis: 20000
    logAbandoned: true
    logDifferentThread: true
    filters: log4j,stat
    connectionProperties: druid.stat.mergeSql=true;druid.stat.logSlowSql=true;druid.stat.slowSqlMillis=3000 # 通过connectProperties属性来打开mergeSql功能；记录执行得慢的SQL
    useGlobalDataSourceStat: true # 合并多个DruidDataSource的监控数据
    druidRegistrationUrl: /druid/* # Druid 监控 Servlet 相关配置参数
    resetEnable: true
    loginUsername: manager
    loginPassword: '12345678'
    filtersUrlPatterns: /* # Druid 监控过滤相关配置参数
    exclusions: '*.js,*.gif,*.jpg,*.jpeg,*.png,*.css,*.ico,*.jsp,/druid/*'
    sessionStatMaxCount: 2000
    sessionStatEnable: true
    principalSessionName: session_user_key
    profileEnable: true